# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default

objects:
 -
   model: rb_ares_cart
   default_link: link_0
 -
   model: rb_ares_cart_0
   default_link: link_0
 -
   model: rb_ares_cart_1
   default_link: link_0

robots:
- 
   model: rb_ares_a
   default_link: rb_ares_a_base_footprint
- 
   model: rb_ares_b
   default_link: rb_ares_b_base_footprint
- 
   model: rb_ares_c
   default_link: rb_ares_c_base_footprint

config:
  # min distance for the simple pick
  min_picking_distance: 0.1
