robotnik_base_control:
  type: ackermann_drive_controller/AckermannDriveController
  traction:
    front_right:
      joint_name: $(arg prefix)traction_joint
      max_speed: 20.0 # rad/s
  steer:
    front_right:
      joint_name: $(arg prefix)steer_joint
      min_angle: -1.57 # rads
      max_angle: 1.57
  linear_speed_limit: 1.0
  linear_acceleration_limit: 1.0
  angular_speed_limit: 2.0
  angular_acceleration_limit: 2.0
  odom_frame: $(arg prefix)odom
  robot_base_frame: $(arg prefix)base_footprint
  odom_broadcast_tf: true
  odom_topic: odom
  command_topic: cmd_vel
  wheel_base: 1.375
  track_width: 0.57
  wheel_diameter: 0.242
  cmd_watchdog_duration: 0.2
  odom_publish_frequency: 100

steer_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)steer_joint

traction_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)traction_joint

elevator_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)elevator_joint

joint_read_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100.0

joint_read_command_controller:
  type: joint_read_command_controller/JointReadCommandController
  publish_rate: 100.0
